### ISSUE TITLE
Bug release version 12c of SOFA

### ISSUE THREAD

**Issue by mhvk** [liberfa/erfa#44]
We should update to 12c; this supposedly includes #40 and #41.

**Comment by eteq** [comment]
Yep, good idea.  There's also #42 (an auspicious issue to be of importance :wink:), which I think looks good except it needs to have the different copyright question dealt with.  So that plus 12c I think is plenty suitable for a new release.

**Comment by rmathar** [comment]
One would actually now upgrade to version 13, released on April 20th.

**Comment by mhvk** [comment]
Thanks, @rmathar; I'll now close this in favour of https://github.com/liberfa/erfa/issues/45
