### ISSUE TITLE
Decide if the version machinery should be more SOFA-like

### ISSUE THREAD

**Issue by eteq** [liberfa/erfa#47]
As detailed further in astropy/astropy#6239 and astropy/astropy#6240, it turns out to be rather complicated to adapt the changes from #42 into the python wrapper used in astropy (which we hope to someday make into a standalone Python library instead of only being accessible through astropy).  So the question is: should the changes in #42 be altered to be more "SOFA-like" ?  Primarily this would mean having the return values be *arguments* instead of actual return values (this is how SOFA "returns" multiple values from one function).  

Also, it's not clear how best to copy over the `config.h` macros with the version info into astropy.  It would be better if those could somehow get injected into the source code (although I'm not sure if that's possible with the C build machinery we're using here... I'm not familiar enough with `autoconf `  to be sure).

Or if it turns out to be easier to solve astropy/astropy#6240 by making the generator machinery more flexible than to make the change here and deal with backwards-compatibility, that's fine too!

cc @olebole

**Comment by sergiopasra** [comment]
I think I can insert VERSION macros in erfaextra.c, using AC_SUBST or something like that...

**Comment by mhvk** [comment]
I think the version routines are working fine as they are in `pyerfa`, so will close. Obviously, feel free to re-open if this is wrong.
