### ISSUE TITLE
SOFA Library Issue 2018-01-30 is available

### ISSUE THREAD

**Issue by jwoillez** [liberfa/erfa#50]
See: http://www.iausofa.org

**Comment by rmathar** [comment]
Obviously one would upgrade to the 15th release of 2019-07-23, not the 14th of 2018-01-30.

**Comment by eteq** [comment]
Oops, for got to close this at the time, but 2018-01-30 was  released in ERFA 1.5.0 (7009153a0fdbc2783e9a3442ddde88b9d9e8b5ef)
