### ISSUE TITLE
Upload releases after 1.4 to Zenodo

### ISSUE THREAD

**Issue by sergiopasra** [liberfa/erfa#57]
The only version of erfa in Zenodo is 1.4. We should upload the next releases or enable the link between Zenodo and github so that every release in github gets an entry in Zenodo

**Comment by eteq** [comment]
Agreed.  But I *thought* this should happen automatically with the Zenodo<>Github integration.  I wonder if the web hook needs to be reset or something?  I'll check for the impending release, but I think regardless we should do as you say here @sergiopasra, as 1.5 and 1.6 probably won't get uploaded given they are already released.

**Comment by eteq** [comment]
Aha, yes, it looks like something may have been mis-configured on the Zenodo side.  I *think* it's fixed now but we will see at the next release (and regardless someone will probably need to do 1.5/1.6)

**Comment by eteq** [comment]
Yep looks like 1.7.0 now is in after I cut the relase so it's just 1.5/1.6 that requires updating now...

**Comment by mhvk** [comment]
I see liberfa 1.5 and 1.6 on https://zenodo.org/record/3564896, so am closing this. Thanks, both!
