### ISSUE TITLE
Wrong version taken for SONAME

### ISSUE THREAD

**Issue by olebole** [liberfa/erfa#59]
When compiling the current version, the SONAME is built from the package version, not from the LIB_VERSION:
```
$ readelf -d ./src/.libs/liberfa.so |grep SONAME
 0x000000000000000e (SONAME)             Library soname: [liberfa.so.1]
```
Looking into `configure.ac` however gives: https://github.com/liberfa/erfa/blob/0bbed2684e58db5f940deb5141f8f3c8afa258f0/configure.ac#L15-L20

So it should actually be liberfa.so.7.
While this is not an issue now, we may face backward incompatible changes in future, #58.
(Just curious: where does the current number come from?)

**Comment by eteq** [comment]
Oh that's weird.  Honestly, I have no idea @olebole... But I agree it seems like it should be 7 not 1...

**Comment by eteq** [comment]
@sergiopasra might have some insight as I think that's where the machinery originates?

**Comment by rmathar** [comment]
If one wants to enforce a specific SONAME, one can add a line

```
soname_spec=lib${PACKAGE}${shrext_cmds}.${VI_CURR}
```

just in front of the

```
AC_OUTPUT
```

in configure.ac. The internal problem seems to be that libtool/automake in link
mode adds -Wl,soname but not the full -Wl,soname,liberfa.so.7 .
For that reason adding -Wl,soname,liberfa.so.7 in src/Makefile.am to LDFLAGS
does not work either.

**Comment by sergiopasra** [comment]
The number 1 is correct, and, in fact, is not the 1 from LIB_VERSION but the difference between `current` and `age`, 7 - 6 = 1
This is explained in the [`libtool` page](https://www.gnu.org/software/libtool/manual/libtool.html#Versioning) but a shorter, perhaps more clear, explanation can be found [here, after the "Warning" in section 4.1](https://autotools.io/libtool/version.html)

**Comment by olebole** [comment]
Ah, this sounds reasonable. Well, as reasonable as Voodoo can be. I think this can be closed.

**Comment by mhvk** [comment]
Thanks, learned something new there!
