### ISSUE TITLE
Fix README.rst -- update release info

### ISSUE THREAD

**Issue by szabi** [liberfa/erfa#66]
README.rst still references version 1.6.0. It would be great to know what 1.7.0 -- the actual current release -- has changed.

**Comment by mhvk** [comment]
This was done in https://github.com/liberfa/erfa/commit/b9a66df5c34e0b89b4d1af902946a8ae4bc10ae8
though it may not have entered the actual release. Very belated thanks for notifying!!

**Comment by szabi** [comment]
@mhvk: the readme still says:

> # Differences from SOFA
> 
> This version of ERFA (**v1.6.0**) is based on SOFA version "20190722", with the differences outlined below.

**Comment by mhvk** [comment]
Oops, that's silly! Re-opening...

**Comment by mhvk** [comment]
But it *will* be fixed by #71(the next ERFA update).

**Comment by mhvk** [comment]
So, actually fixed now...

**Comment by szabi** [comment]
Thanks!
