### ISSUE TITLE
starpm does not work for moderate proper motion/no parallax case

### ISSUE THREAD

**Issue by StuartLittlefair** [liberfa/erfa#68]
See https://github.com/astropy/astropy/issues/10092 for details of this issue emerging in astropy.

If you imagine trying to update a source with proper motion of order 100 mas/yr, but with no distance information. ```erfa.starpm``` tries to treat the object as if it were at "infinite distance". In practice this means setting the parallax to 1e-7 arcseconds (10 Mpc).

In an intermediate step, the ```erfa.starpv``` routine calculates the cartesian position and velocity vectors of your star, but at this large distance the space velocity is >1/2 the speed of light, which ```erfa.starpv``` doesn't like. As a result it sets the velocity vector to 0.

Hence ```erfa.starpm``` doesn't update the position at all.

Perhaps objects with no distance information should be special cased in ```erfa.starpm```?

**Comment by mhvk** [comment]
I think over at the astropy, the solution was to use `pmsafe`, so I think I can close this issue. Obviously, if not, do re-open!
