### ISSUE TITLE
Update to SOFA 17a

### ISSUE THREAD

**Issue by mhvk** [liberfa/erfa#82]
This will fix #76

**Comment by rmathar** [comment]
Just to note:
>Date: Thu, 11 Mar 2021 14:00:36 +0100
>From: "Richard J. Mathar" <mathar@xxx>
>To: sofa@ukho.gov.xxx
>Cc: mathar@xxx
>Subject: SOFA library name conventions
> 
>Dear maintainers of the sofa library:
>In version 17a, the choice of using an underscore in the version (YYYYMMDD_a)
>is not a good idea because it disturbs the debian (including the Ubuntu)
>name convetions, see
>https://manpages.debian.org/buster/dpkg-dev/dpkg-name.1.en.html .
>It would have been simpler just to move the integer of the YYYYMMDD
>forward by a day to be compatible with standard Linux packaging schemes.
>I came across this problem while generating the Ubuntu packages in
>https://build.opensuse.org/package/show/home:rjmathar/iausofa-c .
>
>Best, Richard Mathar

**Comment by mhvk** [comment]
@rmathar - sorry for a belated reply, but please note that we do not maintain SOFA, but just a copy of it with a different license (called ERFA). For contact information on SOFA itself, see http://www.iausofa.org/
