### ISSUE TITLE
proposal: use integer times internally

### ISSUE THREAD

**Issue by spenczar** [liberfa/erfa#93]
As I understand it, erfa's time routines currently represent time as a pair of double-precision floating point numbers. The first is the day part, and the second is a fractional sub-day part, of a Julian date.

I think that using two 64-bit integers would be superior. The first integer could be the Julian date _kiloseconds_, and the second integer could be the femtoseconds of remainder (a femtosecond is 1E-15 seconds, or 1 million nanoseconds).

This system:
 - has a superior range for the values that can be expressed at both the top end (10x more years covered) and bottom end (10,000x finer precision).
 - would use exact arithmetic, avoiding an entire class of nasty bugs, and making numerical algorithms much simpler
 - would probably be slightly faster
 - would permit stable conversion algorithms, since round-tripping from (say) UTC to TAI and back again (as described [here](https://docs.astropy.org/en/stable/time/index.html#time-scales-for-time-deltas)) would not incur any floating point rounding error
 - would prevent user-side confusion like that evinced in https://github.com/astropy/astropy/issues/14455

I realize that this is not a simple change to implement! It would require a rewrite of every aspect of erfa's time-handling code. But I believe it could be a superior system, and since erfa is so fundamental to astronomy, this improvement could have a very wide impact.

Ideally, this change in internal representation would not cause much turmoil for users. Most astronomers interact with erfa through other tools like Astropy which could perhaps manage a transition.

### An example value

As an example, consider the timestamp "2023-03-19 13:52:14.53526." In erfa, that gets represented as two 64-bit floats:

```
2460023.0            # Julian days
0.077982964907407414 # Julian fractional days
```

Note that due to floating point error, the fractional day is ± 4.9e-18 days. The whole day part is exact, however.

I propose it be represented as two 64-bit integers; the first signed, and the second unsigned:

```
212545993          # Julian kiloseconds
937728179931640576 # Julian fractional kiloseconds, in femtoseconds
```

Using Python as a shorthand, here is an example of conversion from floating point to integer:
```python
def convert(jd, jd_fraction):
     ksec1, remainder1 = divmod(jd * 86400, 1000)
     ksec2, remainder2 = divmod(jd_fraction * 86400, 1000)
     jd_kilosec = int(ksec1) + int(ksec2)
     jd_kilosec_fraction = int((remainder1 + remainder2) * 1e15)
     return jd_kilosec, jd_kilosec_fraction

```

### Range of values calculations

64-bit floating point numbers have a maximum whole-number value of 2^53+1; beyond that, the value will no longer be a whole number. So the maximum Julian Day which can be represented is 9,007,199,254,740,993, which is about 2.47E13 years.

A signed 64-bit integer for kiloseconds could represent whole numbers up to 2^63 kiloseconds, which is 2.92E14 years, so this permits about 10x larger range at the top end.

The fractional floating point value for days is precise down to 2^-53 days, which is 1.11E-16 days, or 0.009 nanoseconds.

An unsigned 64-bit integer for the fractional part would need to represent values in [0, 1) kiloseconds, or [0, 1000) seconds. 1 kilosecond is 1e18 femtoseconds, which is less than 2^64, so each integer value can be as single femtosecond and the whole fraction's range is covered. This means the precision floor is 1 femtosecond which is 0.000001 nanoseconds, about 10,000x more precise than erfa's current implementation.

**Comment by spenczar** [comment]
Thanks, I will see about a SOFA change, although I agree it is going to be challenging because of the long history of using two floats.

Could you say more about the advantages of floating point? I don't understand those examples so I must be missing something.

For TAI to TDB, since it is a fixed difference of 32.184 seconds, it should be trivial: you add 3.2184E13 to the second int, and then handle overflows into the next kilosecond; this is the same as how the float works.

What do you mean when you say it is easier to separate the time different ways?

**Comment by mhvk** [comment]
@spenczar - TDB is [barycentric dynamical time](https://en.wikipedia.org/wiki/Barycentric_Dynamical_Time), which runs slightly differently from TAI (TCG runs faster that TAI by ~0.5s/year, TDB is closer to TAI). Note that of course it is in principle possible to do this with integers, and perhaps even more logical given your arguments above, but it is quite a major change for what in the end is arguably not a large benefit.

**Comment by cxwx** [comment]
I doubt 4.9e-18 days really affect? As Few detectors achieve this accuracy.

**Comment by mhvk** [comment]
TDB is used in all pulsar timing experiments.

**Comment by spenczar** [comment]
> @spenczar - TDB is [barycentric dynamical time](https://en.wikipedia.org/wiki/Barycentric_Dynamical_Time), which runs slightly differently from TAI (TCG runs faster that TAI by ~0.5s/year, TDB is closer to TAI). Note that of course it is in principle possible to do this with integers, and perhaps even more logical given your arguments above, but it is quite a major change for what in the end is arguably not a large benefit.

You're right of course about TDB. I was thinking of converting TAI to TT. But as we both say, this isn't really different with integers, and could be simpler.

I think the benefit could be surprisingly significant, since it eliminates a genre of error when datasets are communicated between groups. It lets datasets be queried using exact matches for timestamps, rather than approximate ones, and ensures that time scale conversions are consistent.

I totally agree it is a major change, and not something to be done lightly, but it seems to have many advantages. If the only downside is that we've always done it with floats, perhaps it's time to consider the change. But these are arguments for the IAU SOFA group, not for here :)

**Comment by spenczar** [comment]
@cxwx:
> doubt 4.9e-18 days really affect? As Few detectors achieve this accuracy.

It comes up for large-scale data management. I am working on querying many datasets from different astronomical surveys, and trying to associate observations back to images. In many cases, the only way to do this is to search for matching timestamps.

This needs to be an _exact_ match. I'm looking, say, for a DECam exposure with a MJD of `58725.218278301` in UTC. So _any error at all_ will throw things off, no matter how small.

Rounding errors can occur during time scale conversions because those involve floating point arithmetic operations. This error is not limited to just 4.9E-19 days. It could be much larger as errors accumulate across multiple operations or multiple conversions.

Those errors can persist even if there is a round-trip _through_ processing. So for example, suppose:

1. An observatory emits a TAI timestamp
2. A data reduction group produces a data release which uses UTC timestamps (conversion 1). They may think this is lossless, but they are wrong, because of the floats.
3. An astronomer analyzes the data to look for solar system objects and switches to TDB (conversion 2). Again, not lossless.
4. They report observations to the Minor Planet Center, which accepts an observation, and switches to UTC again. (conversion 3). 

How much error has been introduced at this point, if all actors are using floating point? It could be quite a lot, and that could have been avoided with integer representations internally.

**Comment by mhvk** [comment]
I fear we're going to be stuck with using `time.is_close()`... Partially since transmission often involves writing the time to, e.g., a FITS header keyword (i.e., a long string, in which the integer fraction (binary) cannot be exactly represented. Overall, I think it is not dissimilar to what happens with coordinates as well; one just has to live with rounding errors.

Anyway, as noted, this would be a question for SOFA in the end.
